### ISSUE TITLE
License

### ISSUE THREAD

**Issue by o-gent** [blockloop/blockloop.github.io#1]
Hey! I read your blog post https://www.blockloop.io/smoking-a-turkey-with-prometheus-home-assistant-and-grafana/ from hackernews and enjoyed it a lot (may have to get a software defined radio....)

However I also liked your blog format - very simple. I've been looking around for a while but this clicks with me for some reason. I started messing around with it but realised it doesn't have a license and after digging around, this technically means I can't use it https://softwareengineering.stackexchange.com/questions/148146/open-source-code-with-no-license-can-i-fork-it

Would you want to add a license?

**Comment by blockloop** [comment]
Hey thanks! 

I made the theme after I searched around the internet for a basic theme and found nothing but convoluted messes. I also like that it's unique and I'd prefer that it not become a common theme. I think that a license on this repository would license the content as well as the theme, so I cannot add a license here without also providing it for the content (blog posts). I would have to fork this repository and remove the posts.

**Comment by o-gent** [comment]
Yeah it seems to be a big problem - producing something simple 😅. Fair enough, i'll roll up my sleeves and make my own from scratch which is probably for the best anyway. Thanks!

**Comment by blockloop** [comment]
Yeah I won't report you for taking some ideas from here. I haven't created anything proprietary. I'm not even good with js/css/html so almost all of this is the result of search, copy, paste. The main feature I wanted was centered content that would scale automatically (I think that's called responsive now). I accomplished that with [this](https://github.com/blockloop/blockloop.github.io/blob/b6231083922f0886f6b050138ad80989bfaab877/assets/css/style.css#L99-L109) and [this](https://github.com/blockloop/blockloop.github.io/blob/master/_layouts/default.html#L8-L9). 

I'll look into a fork though.
